---
# task/configure file for install_docker
- name: "Add specified users to group {{ install_docker_group }}"
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ install_docker_group }}"
    append: true
  loop: "{{ install_docker_users }}"

- name: "Enable docker service"
  ansible.builtin.service:
    name: docker
    enabled: true

- name: "Start docker service"
  ansible.builtin.service:
    name: docker
    state: restarted
  when: install_docker_start_service
