---
# task/main file for install_docker
- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import install.yml"
  ansible.builtin.include_tasks: install.yml

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml