---
# task/prerequisites file for install_docker
- name: "Install required roles"
  ansible.builtin.command:
    cmd: "ansible-galaxy install {{ item }}"
  loop: "{{ install_docker_prerequisites_roles }}"
  changed_when: false
  delegate_to: localhost
  run_once: true

- name: "Create group {{ install_docker_group }}"
  ansible.builtin.group:
    name: "{{ install_docker_group }}"
    state: present

- name: "Create directory {{ install_docker_daemon_dir }}"
  ansible.builtin.file:
    path: "{{ install_docker_daemon_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

