---
# task/prerequisites file for install_docker
- name: "Install required roles"
  ansible.builtin.command:
    cmd: "ansible-galaxy install {{ item }}"
  loop: "{{ install_docker_prerequisites_roles }}"
  changed_when: false
  delegate_to: localhost
  run_once: true
